// This file was auto-generated by ML.NET Model Builder.
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Transforms;
    public partial class SatisfactionModel
    {
        public const string RetrainFilePath =  @"C:\Users\Malina\Desktop\facultate\master\an 1 sem 1\big data\set de date kaggle\flight satisfaction\train.csv";
        public const char RetrainSeparatorChar = ',';
        public const bool RetrainHasHeader =  true;
        public const bool RetrainAllowQuoting =  false;

         /// <summary>
        /// Train a new model with the provided dataset.
        /// </summary>
        /// <param name="outputModelPath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet"</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        public static void Train(string outputModelPath, string inputDataFilePath = RetrainFilePath, char separatorChar = RetrainSeparatorChar, bool hasHeader = RetrainHasHeader, bool allowQuoting = RetrainAllowQuoting)
        {
            var mlContext = new MLContext();

            var data = LoadIDataViewFromFile(mlContext, inputDataFilePath, separatorChar, hasHeader, allowQuoting);
            var model = RetrainModel(mlContext, data);
            SaveModel(mlContext, model, data, outputModelPath);
        }

        /// <summary>
        /// Load an IDataView from a file path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        /// <returns>IDataView with loaded training data.</returns>
        public static IDataView LoadIDataViewFromFile(MLContext mlContext, string inputDataFilePath, char separatorChar, bool hasHeader, bool allowQuoting)
        {
            return mlContext.Data.LoadFromTextFile<ModelInput>(inputDataFilePath, separatorChar, hasHeader, allowQuoting: allowQuoting);
        }


        /// <summary>
        /// Save a model at the specified path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="model">Model to save.</param>
        /// <param name="data">IDataView used to train the model.</param>
        /// <param name="modelSavePath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet.</param>
        public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
        {
            // Pull the data schema from the IDataView used for training the model
            DataViewSchema dataViewSchema = data.Schema;

            using (var fs = File.Create(modelSavePath))
            {
                mlContext.Model.Save(model, dataViewSchema, fs);
            }
        }


        /// <summary>
        /// Retrain model using the pipeline generated as part of the training process.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"Gender", @"Gender"),new InputOutputColumnPair(@"Customer Type", @"Customer Type"),new InputOutputColumnPair(@"Type of Travel", @"Type of Travel"),new InputOutputColumnPair(@"Class", @"Class")}, outputKind: OneHotEncodingEstimator.OutputKind.Indicator)      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"column1", @"column1"),new InputOutputColumnPair(@"id", @"id"),new InputOutputColumnPair(@"Age", @"Age"),new InputOutputColumnPair(@"Flight Distance", @"Flight Distance"),new InputOutputColumnPair(@"Inflight wifi service", @"Inflight wifi service"),new InputOutputColumnPair(@"Departure/Arrival time convenient", @"Departure/Arrival time convenient"),new InputOutputColumnPair(@"Ease of Online booking", @"Ease of Online booking"),new InputOutputColumnPair(@"Gate location", @"Gate location"),new InputOutputColumnPair(@"Food and drink", @"Food and drink"),new InputOutputColumnPair(@"Online boarding", @"Online boarding"),new InputOutputColumnPair(@"Seat comfort", @"Seat comfort"),new InputOutputColumnPair(@"Inflight entertainment", @"Inflight entertainment"),new InputOutputColumnPair(@"On-board service", @"On-board service"),new InputOutputColumnPair(@"Leg room service", @"Leg room service"),new InputOutputColumnPair(@"Baggage handling", @"Baggage handling"),new InputOutputColumnPair(@"Checkin service", @"Checkin service"),new InputOutputColumnPair(@"Inflight service", @"Inflight service"),new InputOutputColumnPair(@"Cleanliness", @"Cleanliness"),new InputOutputColumnPair(@"Departure Delay in Minutes", @"Departure Delay in Minutes"),new InputOutputColumnPair(@"Arrival Delay in Minutes", @"Arrival Delay in Minutes")}))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Gender",@"Customer Type",@"Type of Travel",@"Class",@"column1",@"id",@"Age",@"Flight Distance",@"Inflight wifi service",@"Departure/Arrival time convenient",@"Ease of Online booking",@"Gate location",@"Food and drink",@"Online boarding",@"Seat comfort",@"Inflight entertainment",@"On-board service",@"Leg room service",@"Baggage handling",@"Checkin service",@"Inflight service",@"Cleanliness",@"Departure Delay in Minutes",@"Arrival Delay in Minutes"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"satisfaction",inputColumnName:@"satisfaction",addKeyValueAnnotationsAsText:false))      
                                    .Append(mlContext.MulticlassClassification.Trainers.LightGbm(new LightGbmMulticlassTrainer.Options(){NumberOfLeaves=216,NumberOfIterations=2837,MinimumExampleCountPerLeaf=20,LearningRate=0.011843090497324273,LabelColumnName=@"satisfaction",FeatureColumnName=@"Features",Booster=new GradientBooster.Options(){SubsampleFraction=0.07601337155645203,FeatureFraction=0.99999999,L1Regularization=2E-10,L2Regularization=0.044516607381898325},MaximumBinCountPerFeature=144}))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
 