// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
public partial class SatisfactionModel
{
    /// <summary>
    /// model input class for SatisfactionModel.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [LoadColumn(0)]
        [ColumnName(@"column1")]
        public float Column1 { get; set; }

        [LoadColumn(1)]
        [ColumnName(@"id")]
        public float Id { get; set; }

        [LoadColumn(2)]
        [ColumnName(@"Gender")]
        public string Gender { get; set; }

        [LoadColumn(3)]
        [ColumnName(@"Customer Type")]
        public string Customer_Type { get; set; }

        [LoadColumn(4)]
        [ColumnName(@"Age")]
        public float Age { get; set; }

        [LoadColumn(5)]
        [ColumnName(@"Type of Travel")]
        public string Type_of_Travel { get; set; }

        [LoadColumn(6)]
        [ColumnName(@"Class")]
        public string Class { get; set; }

        [LoadColumn(7)]
        [ColumnName(@"Flight Distance")]
        public float Flight_Distance { get; set; }

        [LoadColumn(8)]
        [ColumnName(@"Inflight wifi service")]
        public float Inflight_wifi_service { get; set; }

        [LoadColumn(9)]
        [ColumnName(@"Departure/Arrival time convenient")]
        public float Departure_Arrival_time_convenient { get; set; }

        [LoadColumn(10)]
        [ColumnName(@"Ease of Online booking")]
        public float Ease_of_Online_booking { get; set; }

        [LoadColumn(11)]
        [ColumnName(@"Gate location")]
        public float Gate_location { get; set; }

        [LoadColumn(12)]
        [ColumnName(@"Food and drink")]
        public float Food_and_drink { get; set; }

        [LoadColumn(13)]
        [ColumnName(@"Online boarding")]
        public float Online_boarding { get; set; }

        [LoadColumn(14)]
        [ColumnName(@"Seat comfort")]
        public float Seat_comfort { get; set; }

        [LoadColumn(15)]
        [ColumnName(@"Inflight entertainment")]
        public float Inflight_entertainment { get; set; }

        [LoadColumn(16)]
        [ColumnName(@"On-board service")]
        public float On_board_service { get; set; }

        [LoadColumn(17)]
        [ColumnName(@"Leg room service")]
        public float Leg_room_service { get; set; }

        [LoadColumn(18)]
        [ColumnName(@"Baggage handling")]
        public float Baggage_handling { get; set; }

        [LoadColumn(19)]
        [ColumnName(@"Checkin service")]
        public float Checkin_service { get; set; }

        [LoadColumn(20)]
        [ColumnName(@"Inflight service")]
        public float Inflight_service { get; set; }

        [LoadColumn(21)]
        [ColumnName(@"Cleanliness")]
        public float Cleanliness { get; set; }

        [LoadColumn(22)]
        [ColumnName(@"Departure Delay in Minutes")]
        public float Departure_Delay_in_Minutes { get; set; }

        [LoadColumn(23)]
        [ColumnName(@"Arrival Delay in Minutes")]
        public float Arrival_Delay_in_Minutes { get; set; }

        [LoadColumn(24)]
        [ColumnName(@"satisfaction")]
        public string Satisfaction { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for SatisfactionModel.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName(@"column1")]
        public float Column1 { get; set; }

        [ColumnName(@"id")]
        public float Id { get; set; }

        [ColumnName(@"Gender")]
        public float[] Gender { get; set; }

        [ColumnName(@"Customer Type")]
        public float[] Customer_Type { get; set; }

        [ColumnName(@"Age")]
        public float Age { get; set; }

        [ColumnName(@"Type of Travel")]
        public float[] Type_of_Travel { get; set; }

        [ColumnName(@"Class")]
        public float[] Class { get; set; }

        [ColumnName(@"Flight Distance")]
        public float Flight_Distance { get; set; }

        [ColumnName(@"Inflight wifi service")]
        public float Inflight_wifi_service { get; set; }

        [ColumnName(@"Departure/Arrival time convenient")]
        public float Departure_Arrival_time_convenient { get; set; }

        [ColumnName(@"Ease of Online booking")]
        public float Ease_of_Online_booking { get; set; }

        [ColumnName(@"Gate location")]
        public float Gate_location { get; set; }

        [ColumnName(@"Food and drink")]
        public float Food_and_drink { get; set; }

        [ColumnName(@"Online boarding")]
        public float Online_boarding { get; set; }

        [ColumnName(@"Seat comfort")]
        public float Seat_comfort { get; set; }

        [ColumnName(@"Inflight entertainment")]
        public float Inflight_entertainment { get; set; }

        [ColumnName(@"On-board service")]
        public float On_board_service { get; set; }

        [ColumnName(@"Leg room service")]
        public float Leg_room_service { get; set; }

        [ColumnName(@"Baggage handling")]
        public float Baggage_handling { get; set; }

        [ColumnName(@"Checkin service")]
        public float Checkin_service { get; set; }

        [ColumnName(@"Inflight service")]
        public float Inflight_service { get; set; }

        [ColumnName(@"Cleanliness")]
        public float Cleanliness { get; set; }

        [ColumnName(@"Departure Delay in Minutes")]
        public float Departure_Delay_in_Minutes { get; set; }

        [ColumnName(@"Arrival Delay in Minutes")]
        public float Arrival_Delay_in_Minutes { get; set; }

        [ColumnName(@"satisfaction")]
        public uint Satisfaction { get; set; }

        [ColumnName(@"Features")]
        public float[] Features { get; set; }

        [ColumnName(@"PredictedLabel")]
        public string PredictedLabel { get; set; }

        [ColumnName(@"Score")]
        public float[] Score { get; set; }

    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath("SatisfactionModel.mlnet");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }

    /// <summary>
    /// Use this method to predict scores for all possible labels.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        var result = predEngine.Predict(input);
        return GetSortedScoresWithLabels(result);
    }

    /// <summary>
    /// Map the unlabeled result score array to the predicted label names.
    /// </summary>
    /// <param name="result">Prediction to get the labeled scores from.</param>
    /// <returns>Ordered list of label and score.</returns>
    /// <exception cref="Exception"></exception>
    public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
    {
        var unlabeledScores = result.Score;
        var labelNames = GetLabels(result);

        Dictionary<string, float> labledScores = new Dictionary<string, float>();
        for (int i = 0; i < labelNames.Count(); i++)
        {
            // Map the names to the predicted result score array
            var labelName = labelNames.ElementAt(i);
            labledScores.Add(labelName.ToString(), unlabeledScores[i]);
        }

        return labledScores.OrderByDescending(c => c.Value);
    }

    /// <summary>
    /// Get the ordered label names.
    /// </summary>
    /// <param name="result">Predicted result to get the labels from.</param>
    /// <returns>List of labels.</returns>
    /// <exception cref="Exception"></exception>
    private static IEnumerable<string> GetLabels(ModelOutput result)
    {
        var schema = PredictEngine.Value.OutputSchema;

        var labelColumn = schema.GetColumnOrNull("satisfaction");
        if (labelColumn == null)
        {
            throw new Exception("satisfaction column not found. Make sure the name searched for matches the name in the schema.");
        }

        // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
        var keyNames = new VBuffer<ReadOnlyMemory<char>>();
        labelColumn.Value.GetKeyValues(ref keyNames);
        return keyNames.DenseValues().Select(x => x.ToString());
    }

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }
}
