// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect_Zboruri_Cilibia_Malina.Data;

#nullable disable

namespace Proiect_Zboruri_Cilibia_Malina.Migrations
{
    [DbContext(typeof(FlightContext))]
    partial class FlightContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proiect_Zboruri_Cilibia_Malina.Models.Airline", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("Proiect_Zboruri_Cilibia_Malina.Models.Airport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("ID");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("Proiect_Zboruri_Cilibia_Malina.Models.Booking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightID")
                        .HasColumnType("int");

                    b.Property<int>("PassengerID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TicketClassID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FlightID");

                    b.HasIndex("PassengerID");

                    b.HasIndex("TicketClassID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Proiect_Zboruri_Cilibia_Malina.Models.Flight", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AirlineID")
                        .HasColumnType("int");

                    b.Property<int>("AirportID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.HasIndex("AirlineID");

                    b.HasIndex("AirportID");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Proiect_Zboruri_Cilibia_Malina.Models.Passenger", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("Proiect_Zboruri_Cilibia_Malina.Models.SatisfactionPredictionHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("Age")
                        .HasColumnType("real");

                    b.Property<float>("ArrivalDelayInMinutes")
                        .HasColumnType("real");

                    b.Property<float>("BaggageHandling")
                        .HasColumnType("real");

                    b.Property<float>("CheckinService")
                        .HasColumnType("real");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Cleanliness")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("DepartureArrivalTimeConvenient")
                        .HasColumnType("real");

                    b.Property<float>("DepartureDelayInMinutes")
                        .HasColumnType("real");

                    b.Property<float>("EaseOfOnlineBooking")
                        .HasColumnType("real");

                    b.Property<float>("FlightDistance")
                        .HasColumnType("real");

                    b.Property<float>("FoodAndDrink")
                        .HasColumnType("real");

                    b.Property<float>("GateLocation")
                        .HasColumnType("real");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("InflightEntertainment")
                        .HasColumnType("real");

                    b.Property<float>("InflightService")
                        .HasColumnType("real");

                    b.Property<float>("InflightWifiService")
                        .HasColumnType("real");

                    b.Property<float>("LegRoomService")
                        .HasColumnType("real");

                    b.Property<float>("OnBoardService")
                        .HasColumnType("real");

                    b.Property<float>("OnlineBoarding")
                        .HasColumnType("real");

                    b.Property<string>("PredictedSatisfaction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SeatComfort")
                        .HasColumnType("real");

                    b.Property<string>("TypeOfTravel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PredictionHistories");
                });

            modelBuilder.Entity("Proiect_Zboruri_Cilibia_Malina.Models.TicketClass", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.ToTable("TicketClasses");
                });

            modelBuilder.Entity("Proiect_Zboruri_Cilibia_Malina.Models.Booking", b =>
                {
                    b.HasOne("Proiect_Zboruri_Cilibia_Malina.Models.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proiect_Zboruri_Cilibia_Malina.Models.Passenger", "Passenger")
                        .WithMany("Bookings")
                        .HasForeignKey("PassengerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proiect_Zboruri_Cilibia_Malina.Models.TicketClass", "TicketClass")
                        .WithMany("Bookings")
                        .HasForeignKey("TicketClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");

                    b.Navigation("TicketClass");
                });

            modelBuilder.Entity("Proiect_Zboruri_Cilibia_Malina.Models.Flight", b =>
                {
                    b.HasOne("Proiect_Zboruri_Cilibia_Malina.Models.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proiect_Zboruri_Cilibia_Malina.Models.Airport", "Airport")
                        .WithMany("Flights")
                        .HasForeignKey("AirportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Proiect_Zboruri_Cilibia_Malina.Models.Airline", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Proiect_Zboruri_Cilibia_Malina.Models.Airport", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Proiect_Zboruri_Cilibia_Malina.Models.Flight", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Proiect_Zboruri_Cilibia_Malina.Models.Passenger", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Proiect_Zboruri_Cilibia_Malina.Models.TicketClass", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
